### ISSUE TITLE
I am getting zero interactions with residues when performing MFE analysis  

### ISSUE THREAD

**Issue by bio-ux** [GunnerLab/Stable-MCCE#121]
Hello, 

I am sorry if my query is a little bit basic, I am trying to learn a new tool.  

I performed the pKa calculation using the 4PTI protein structure, and I tried to use the MFE analysis tool. 
 I did this analysis for the ASP A0003 residue at pKa 4.216 (which is the pKa from pK.out value)

I got the interaction with all residues equal 0 ? is that make sense? I have no idea how to judge my results where that there is no user manual or any clear tutorial 

I am using MCCE-2.5 version

I tried to use the MFE tool which came originally with the mcce2.5 software and also the one uploaded here... I got the same result 

here is the output that I got 

`Residue ASP-A0003_ pKa/Em=4.216
=================================
Terms          pH     meV    Kcal
---------------------------------
vdw0        -0.01   -0.44   -0.01
vdw1        -0.10   -6.09   -0.14
tors        -0.01   -0.81   -0.02
ebkb        -0.36  -20.82   -0.49
dsol         0.17    9.85    0.23
offset       0.00    0.00    0.00
pH&pK0       0.53   30.99    0.73
Eh&Em0       0.00    0.00    0.00
-TS          0.30   17.55    0.41
residues     0.00    0.00    0.00
*********************************
TOTAL        0.52   30.25    0.71
*********************************
NTRA0001_    0.00    0.00    0.00
ARGA0001_    0.00    0.00    0.00
PROA0002_    0.00    0.00    0.00
ASPA0003_    0.00    0.00    0.00
PHEA0004_    0.00    0.00    0.00
CYDA0005_    0.00    0.00    0.00
LEUA0006_    0.00    0.00    0.00
GLUA0007_    0.00    0.00    0.00
PROA0008_    0.00    0.00    0.00
PROA0009_    0.00    0.00    0.00
TYRA0010_    0.00    0.00    0.00
THRA0011_    0.00    0.00    0.00
PROA0013_    0.00    0.00    0.00
CYDA0014_    0.00    0.00    0.00
LYSA0015_    0.00    0.00    0.00
ALAA0016_    0.00    0.00    0.00
ARGA0017_    0.00    0.00    0.00
ILEA0018_    0.00    0.00    0.00
ILEA0019_    0.00    0.00    0.00
ARGA0020_    0.00    0.00    0.00
TYRA0021_    0.00    0.00    0.00
PHEA0022_    0.00    0.00    0.00
TYRA0023_    0.00    0.00    0.00
ASNA0024_    0.00    0.00    0.00
ALAA0025_    0.00    0.00    0.00
LYSA0026_    0.00    0.00    0.00
ALAA0027_    0.00    0.00    0.00
LEUA0029_    0.00    0.00    0.00
CYDA0030_    0.00    0.00    0.00
GLNA0031_    0.00    0.00    0.00
THRA0032_    0.00    0.00    0.00
PHEA0033_    0.00    0.00    0.00
VALA0034_    0.00    0.00    0.00
TYRA0035_    0.00    0.00    0.00
CYDA0038_    0.00    0.00    0.00
ARGA0039_    0.00    0.00    0.00
ALAA0040_    0.00    0.00    0.00
LYSA0041_    0.00    0.00    0.00
ARGA0042_    0.00    0.00    0.00
ASNA0043_    0.00    0.00    0.00
ASNA0044_    0.00    0.00    0.00
PHEA0045_    0.00    0.00    0.00
LYSA0046_    0.00    0.00    0.00
SERA0047_    0.00    0.00    0.00
ALAA0048_    0.00    0.00    0.00
GLUA0049_    0.00    0.00    0.00
ASPA0050_    0.00    0.00    0.00
CYDA0051_    0.00    0.00    0.00
META0052_    0.00    0.00    0.00
ARGA0053_    0.00    0.00    0.00
THRA0054_    0.00    0.00    0.00
CYDA0055_    0.00    0.00    0.00
ALAA0058_    0.00    0.00    0.00
CTRA0058_    0.00    0.00    0.00
=================================`

**Comment by newbooks** [comment]
Check if you have a folder called "energies" and files named "*.opp" under your working directory.

mcce2.5 uses a compressed file energy.opp and it has to be decompressed by "zopp -x energy.opp" if I remember it correctly.

**Comment by newbooks** [comment]
If you use the new code, it is pretty easy to rerun all steps:

step1.py 4PTI.pdb --dry
step2.py
step3.py
step4.py

**Comment by bio-ux** [comment]
> Check if you have a folder called "energies" and files named "*.opp" under your working directory.
> 
> mcce2.5 uses a compressed file energy.opp and it has to be decompressed by "zopp -x energy.opp" if I remember it correctly.

thanks a lot for your reply. 

actually I performed this step. 



> If you use the new code, it is pretty easy to rerun all steps:
> 
> step1.py 4PTI.pdb --dry
> step2.py
> step3.py
> step4.py

I will try the new code thx a lot.

**Comment by bio-ux** [comment]
Hi, finally it worked with me but after simple modification in the code, from another mfe.py file

firstly the "has_key" method is no longer supported by python3.x , also "argparse" didn't work with python2.x. 

so I edited the "print_crg(RES)" function, to be compatible with python2 and it worked fine with me
