### ISSUE TITLE
Why MCCE cant find the tpl file for HEME PDD, NTG and PAA ?

### ISSUE THREAD

**Issue by bio-ux** [GunnerLab/Stable-MCCE#150]
Hi, 
I followed the steps described in MCCE documentation, but I can see that MCCE generated the new.tpl for HEM, NTG, PDD and PAA .

it seems that MCCE cant see the tpl files for those molecules. 
I checked the param04 folder, all required tpls are there already ! 

How could I solve this issue ?

**Comment by bio-ux** [comment]
the protein I am using is the same as in the documentation (1AKK.pdb)

**Comment by newbooks** [comment]
In Stable-MCCE directory, run "git pull", "make clean", and "make" to update the code. Probably the ftpl files of NTG, PAA, PDD and HEM were added after you first downloaded the code.

**Comment by bio-ux** [comment]
Oh Thanks, it worked perfectly.
