### ISSUE TITLE
A quick question about bkn contribution to the calculated Em

### ISSUE THREAD

**Issue by ghost** [GunnerLab/Stable-MCCE#177]
In my study, I need to know what factors led to the calculated Em potential of the cofactor in the study. 
I performed the MFE.py analysis, and I intersted to breakdown the backbone contribution to see which residues are contributing to this term. 

I dont know how to that, could you help ? Is there any tool available for this .. thanks

**Comment by newbooks** [comment]
Here is a description of mfe.py command: https://gunnerlab.github.io/Stable-MCCE/tools/#mfepy

To analyze the contributing factors at Em, you will need to run a Eh titration that covers the midpoint. If the midpoint is out of titration range, you can choose a Eh/pH point.

Examples (residue ID is from pK.out file):
mfe.py HEM+A0105_                 # do mfe analysis at midpoint
mfe.py HEM+A0105_ -c 0.1       # do mfe with pairwise interaction display cut off at 0.1 ph unit
mfe.py HEM+A0105_ -p 200     # do mfe at Eh 200 mV
