### ISSUE TITLE
Microstates folder not created even when MS_OUT is set to true

### ISSUE THREAD

**Issue by samberry19** [GunnerLab/Stable-MCCE#217]
I am trying to extract information about individual microstates of my protein and am following the tutorial here: https://gunnerlab.github.io/Stable-MCCE/ms_analysis/. I'm just doing so with the 4PTI.pdb example to get started. However, when I run step4.py with the --ms option, no ms_out folder is created. I checked the run.prm file and MS_OUT is set to true ("t"), so that is not the problem. I am running MCCE version 2.7 that was last updated this past June. Thanks for any help!

**Comment by umeshkhaniya** [comment]
Do you have the output from step 3 (head3.lst and energies)? You need these files as input for your step4. Make sure to run step 1, step2, and step 3 first and then you can run step4 using --ms option. I tried with 4PTI.pdb and it worked for me. You can also update the mcce.
