### ISSUE TITLE
Fatal error Step 3 - example 1dpx.pdb

### ISSUE THREAD

**Issue by tkcaccia** [GunnerLab/Stable-MCCE#238]
I report this issue in the step3.py   

 WARNING: Delphi failed at focusing depth 1 of NTR01A0001_001, retry
   FATAL: too many failed delphi runs (10), quitting...
   Fatal error reported by conf_energies(), QUIT.
11:17:05: Thread 0: finishing
11:17:09: Main: join thread 0
11:17:09: Main: Done

**Comment by newbooks** [comment]
This is usually caused by delphi error. To test it, run

delphi

Check if delphi program can run.
